### ISSUE TITLE
feat: set deployment size on trust manager

### ISSUE THREAD

**Issue by scottd018** [tbd-paas/platform-config-operator#2]
Add the logic to adjust a trust manager resource based on it's deployment size.  Logic should be implemented here > https://github.com/tbd-paas/platform-config-operator/blob/main/apis/deploy/v1alpha1/platformconfig/mutate/trust_manager_config.go#L38

1. A `PlatformConfig` object looks like this > https://github.com/tbd-paas/platform-config-operator/blob/main/config/samples/deploy_v1alpha1_platformconfig.yaml#L9
2. A `TrustManager` object is deployed from a `PlatformConfig` object via this operator.  It looks like this > https://github.com/tbd-paas/capabilities-certificates-operator/blob/main/config/samples/certificates_v1alpha1_trustmanager.yaml
3. When the `spec.certificates.deploymentSize` field of the `PlatformConfig` object is modified, the underlying `TrustManager` resource should be adjusted to match the appropriate deploymentsize.
4. `*.deploymentSize` is only ever equal to `small`, `medium`, or `large`.  See https://github.com/tbd-paas/platform-config-operator/blob/main/apis/deploy/v1alpha1/platformconfig_types.go#L68 for the enumerables.

The following values should be set set for each deployment size:

`small`:

```yaml
    replicas: 1
    resources:
      requests:
        cpu: "25m"
        memory: "32Mi"
      limits:
        memory: "64Mi"
```

`medium`:

```yaml
    replicas: 1
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        memory: "96Mi"
```

`large`:

```yaml
    replicas: 2
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        memory: "96Mi"
```

Be sure to add unit tests for this function.
